const projects = [
  {slug:'gadai-mulia',title:'Gadai Mulia',category:'Fintech / Mobile',filters:['Fintech','Mobile'],role:'Product design, UX/UI',year:'2024',image:'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&q=85',desc:'A digital pawnbroking experience designed to make financial transactions more accessible and understandable.',tone:'sand'},
  {slug:'synqra',title:'Synqra',category:'SaaS / Productivity',filters:['SaaS','Web'],role:'Product strategy, UX/UI',year:'2024',image:'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=85',desc:'A meeting notes and workflow platform that helps teams turn discussions into actionable work.',tone:'blue'},
  {slug:'drawtopia',title:'Drawtopia',category:'AI / Creative platform',filters:['AI','Web'],role:'Interaction design, visual system',year:'2023',image:'https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?auto=format&fit=crop&w=1200&q=85',desc:'A story-generation experience designed to help people create imaginative content through AI-assisted interaction.',tone:'violet'},
  {slug:'task-sharing',title:'Task-sharing platform',category:'Marketplace / Gig economy',filters:['Marketplace','Mobile'],role:'UX research, end-to-end design',year:'2023',image:'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=85',desc:'A platform connecting people who need tasks completed with trusted service providers.',tone:'cream'},
  {slug:'threat-intelligence',title:'Threat intelligence dashboard',category:'Enterprise / Data visualization',filters:['Enterprise','Web'],role:'Information architecture, UI',year:'2022',image:'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=85',desc:'A structured dashboard for monitoring threats, incidents, and security-related information.',tone:'slate'},
  {slug:'omnichannel',title:'Omnichannel platform',category:'SaaS / Communication',filters:['SaaS','Web'],role:'Product design, design system',year:'2022',image:'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=85',desc:'A unified communication product for teams managing conversations across multiple channels.',tone:'rose'},
  {slug:'wedding-dashboard',title:'Wedding planning dashboard',category:'Lifestyle / Web application',filters:['Web'],role:'UX/UI design',year:'2021',image:'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=85',desc:'A planning workspace for organizing wedding tasks, vendors, schedules, and budgets.',tone:'stone'},
  {slug:'english-learning',title:'TOEFL & IELTS learning',category:'Education / Learning platform',filters:['Education','Mobile','Web'],role:'UX/UI design, prototyping',year:'2021',image:'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=85',desc:'A focused learning experience for people preparing for English proficiency examinations.',tone:'gold'}
];
const app = document.querySelector('#app');
const template = (strings,...values) => strings.reduce((out,s,i)=>out+s+(values[i]??''),'');
const card = (p, i=0) => template`<article class="project-card ${i < 3 ? 'feature-card':''}" data-project="${p.slug}" tabindex="0" role="button" aria-label="View ${p.title} case study"><div class="project-image tone-${p.tone}"><img loading="lazy" src="${p.image}" alt="A visual for ${p.title}" /></div><div class="project-info"><div><p>${p.category}</p><h3>${p.title}</h3></div><span>${p.year} <i>↗</i></span></div><p class="project-desc">${p.desc}</p></article>`;
function home(){return template`<section class="hero reveal"><p class="eyebrow">Senior product designer · Jakarta</p><h1>Hello, I’m Hisyam — a senior UX/UI and product designer focused on creating clear, useful, and engaging digital experiences.</h1><div class="hero-bottom"><p>I work across mobile and web products, combining research, interaction design, and visual systems to make complex ideas feel simple.</p><p class="muted">Based in Jakarta, Indonesia <br>Available for selected projects</p></div></section><section class="experience reveal"><p class="section-number">01 / Selected experience</p><h2>Currently working across product, UX/UI, and digital experiences.</h2><div class="experience-list"><span>Serba Mulia Group<br><small>Product and UX/UI design</small></span><span>Peak Haven<br><small>Digital product design</small></span><span>Gadai Mulia<br><small>Fintech product design</small></span><span>Synqra<br><small>SaaS product design</small></span><span>Drawtopia<br><small>AI creative platform</small></span><span>Base44<br><small>AI productivity tools</small></span></div></section><section class="work-preview reveal"><div class="section-heading"><p class="section-number">02 / Portfolio</p><h2>Selected work</h2><a href="#work">View all work <span>↗</span></a></div><div class="project-grid">${projects.slice(0,6).map(card).join('')}</div></section>`}
function about(){return template`<section class="page-intro reveal"><p class="section-number">02 / About</p><h1>Designing systems that help people make sense of complex things.</h1></section><section class="about-grid reveal"><div><p class="lead">I’m a product designer with more than 15 years of experience creating digital products for fintech, SaaS, marketplaces, education, security, communication, and AI-powered platforms.</p><p>I enjoy shaping a product from the early question through to a considered interface and a practical handoff. My work is grounded in attention to people, business context, and the small details that make a product feel trustworthy.</p></div><div class="side-note"><p>Working principles</p><ol><li>Make the complex legible.</li><li>Build with the team, not in isolation.</li><li>Give systems room to grow.</li></ol></div></section><section class="capabilities reveal"><p class="section-number">Capabilities</p><div><h2>From product direction to the last interaction detail.</h2><div class="cap-list"><span>Product strategy</span><span>UX research</span><span>User flows & IA</span><span>Wireframing</span><span>Prototyping</span><span>Interaction design</span><span>Visual design</span><span>Design systems</span><span>Usability testing</span><span>Design handoff</span><span>Competitor analysis</span></div></div></section><section class="tools reveal"><p>Tools & workflow</p><p>Figma, FigJam, Adobe tools, Photopea, Notion, and AI-assisted design and research tools. I work openly with product, engineering, and stakeholders to turn decisions into momentum.</p></section>`}
function work(){const filters=['All','Fintech','SaaS','Mobile','Web','AI','Enterprise','Marketplace','Education'];return template`<section class="page-intro work-intro reveal"><p class="section-number">03 / Work</p><h1>A selection of products made clearer, more useful, and easier to move through.</h1></section><section class="all-work reveal"><div class="filters" role="toolbar" aria-label="Filter projects">${filters.map(x=>`<button class="${x==='All'?'active':''}" data-filter="${x}">${x}</button>`).join('')}</div><div class="work-grid">${projects.map((p,i)=>card(p,i)).join('')}</div></section>`}
function render(){let route=location.hash.slice(1)||'home'; if(!['home','about','work'].includes(route))route='home'; app.innerHTML=route==='home'?home():route==='about'?about():work(); document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.dataset.route===route)); bind(); window.scrollTo({top:0,behavior:'instant'});}
function bind(){document.querySelectorAll('[data-project]').forEach(el=>{el.addEventListener('click',()=>openProject(el.dataset.project));el.addEventListener('keydown',e=>{if(e.key==='Enter')openProject(el.dataset.project)})});document.querySelectorAll('[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b===btn));document.querySelectorAll('.work-grid .project-card').forEach(el=>{let p=projects.find(x=>x.slug===el.dataset.project);el.hidden=btn.dataset.filter!=='All'&&!p.filters.includes(btn.dataset.filter)})}))}
const dialog=document.querySelector('.project-dialog');
function openProject(slug){const p=projects.find(x=>x.slug===slug);document.querySelector('#dialog-content').innerHTML=template`<div class="case-hero"><p>${p.category} · ${p.year}</p><h2>${p.title}</h2><p>${p.desc}</p></div><img class="case-image" src="${p.image}" alt="${p.title} project visual"/><div class="case-grid"><div><p class="section-number">Context</p><h3>A focused product problem, approached with care.</h3></div><div><p>This case study is structured as a ready-to-complete project record. The work centered on translating a complex workflow into a calm, navigable product experience.</p><p><b>Role</b><br>${p.role}</p><p><b>Approach</b><br>Discovery, user flows, wireframes, interface design, prototyping, and developer handoff.</p></div></div><div class="case-stages"><span>01<br><b>Understand</b><small>Clarify the context, users, and constraints.</small></span><span>02<br><b>Structure</b><small>Map flows and create a usable information model.</small></span><span>03<br><b>Refine</b><small>Build a visual system that makes the work feel natural.</small></span></div><p class="case-outcome"><span>Outcome</span>A scalable product foundation with clear patterns for the team to develop and extend.</p>`;dialog.showModal();document.body.classList.add('modal-open')}
document.querySelector('.dialog-close').onclick=()=>{dialog.close();document.body.classList.remove('modal-open')};dialog.addEventListener('click',e=>{if(e.target===dialog){dialog.close();document.body.classList.remove('modal-open')}});
document.querySelector('.menu-toggle').onclick=()=>{let b=document.querySelector('.menu-toggle'), n=document.querySelector('nav');b.setAttribute('aria-expanded',!n.classList.toggle('open'))};
document.querySelector('.back-top').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});document.querySelector('#year').textContent=new Date().getFullYear();
window.addEventListener('hashchange',render);render();
